2024-03-31 09:46:00,182 INFO    MainThread:3306724 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-31 09:46:00,183 INFO    MainThread:3306724 [wandb_setup.py:_flush():76] Configure stats pid to 3306724
2024-03-31 09:46:00,183 INFO    MainThread:3306724 [wandb_setup.py:_flush():76] Loading settings from /home/chenqin.p/.config/wandb/settings
2024-03-31 09:46:00,183 INFO    MainThread:3306724 [wandb_setup.py:_flush():76] Loading settings from /cpfs01/user/chenqin.p/dyh/MOELoRA-peft/wandb/settings
2024-03-31 09:46:00,183 INFO    MainThread:3306724 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-31 09:46:00,183 INFO    MainThread:3306724 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-31 09:46:00,183 INFO    MainThread:3306724 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'run_mlora.py', 'program_abspath': '/cpfs01/user/chenqin.p/dyh/MOELoRA-peft/run_mlora.py', 'program': '/cpfs01/user/chenqin.p/dyh/MOELoRA-peft/run_mlora.py'}
2024-03-31 09:46:00,183 INFO    MainThread:3306724 [wandb_init.py:_log_setup():526] Logging user logs to /cpfs01/user/chenqin.p/dyh/MOELoRA-peft/wandb/run-20240331_094600-ygk4z0sb/logs/debug.log
2024-03-31 09:46:00,183 INFO    MainThread:3306724 [wandb_init.py:_log_setup():527] Logging internal logs to /cpfs01/user/chenqin.p/dyh/MOELoRA-peft/wandb/run-20240331_094600-ygk4z0sb/logs/debug-internal.log
2024-03-31 09:46:00,183 INFO    MainThread:3306724 [wandb_init.py:init():566] calling init triggers
2024-03-31 09:46:00,183 INFO    MainThread:3306724 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-31 09:46:00,183 INFO    MainThread:3306724 [wandb_init.py:init():616] starting backend
2024-03-31 09:46:00,183 INFO    MainThread:3306724 [wandb_init.py:init():620] setting up manager
2024-03-31 09:46:00,184 INFO    MainThread:3306724 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-03-31 09:46:00,185 INFO    MainThread:3306724 [wandb_init.py:init():628] backend started and connected
2024-03-31 09:46:00,186 INFO    MainThread:3306724 [wandb_init.py:init():720] updated telemetry
2024-03-31 09:46:00,190 INFO    MainThread:3306724 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-31 09:46:32,007 INFO    MainThread:3306724 [wandb_run.py:_on_init():2262] communicating current version
2024-03-31 09:46:33,016 INFO    MainThread:3306724 [wandb_run.py:_on_init():2271] got version response upgrade_message: "wandb version 0.16.5 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-03-31 09:46:33,016 INFO    MainThread:3306724 [wandb_init.py:init():804] starting run threads in backend
2024-03-31 09:46:35,639 INFO    MainThread:3306724 [wandb_run.py:_console_start():2241] atexit reg
2024-03-31 09:46:35,640 INFO    MainThread:3306724 [wandb_run.py:_redirect():2096] redirect: wrap_raw
2024-03-31 09:46:35,640 INFO    MainThread:3306724 [wandb_run.py:_redirect():2161] Wrapping output streams.
2024-03-31 09:46:35,640 INFO    MainThread:3306724 [wandb_run.py:_redirect():2186] Redirects installed.
2024-03-31 09:46:35,641 INFO    MainThread:3306724 [wandb_init.py:init():847] run started, returning control to user process
2024-03-31 09:46:35,642 INFO    MainThread:3306724 [wandb_run.py:_config_callback():1343] config_cb None None {'vocab_size': 32000, 'max_position_embeddings': 4096, 'hidden_size': 4096, 'intermediate_size': 11008, 'num_hidden_layers': 32, 'num_attention_heads': 32, 'num_key_value_heads': 32, 'hidden_act': 'silu', 'initializer_range': 0.02, 'rms_norm_eps': 1e-05, 'pretraining_tp': 1, 'use_cache': True, 'rope_scaling': None, 'return_dict': True, 'output_hidden_states': False, 'output_attentions': False, 'torchscript': False, 'torch_dtype': 'float16', 'use_bfloat16': False, 'tf_legacy_loss': False, 'pruned_heads': {}, 'tie_word_embeddings': False, 'is_encoder_decoder': False, 'is_decoder': False, 'cross_attention_hidden_size': None, 'add_cross_attention': False, 'tie_encoder_decoder': False, 'max_length': 20, 'min_length': 0, 'do_sample': False, 'early_stopping': False, 'num_beams': 1, 'num_beam_groups': 1, 'diversity_penalty': 0.0, 'temperature': 1.0, 'top_k': 50, 'top_p': 1.0, 'typical_p': 1.0, 'repetition_penalty': 1.0, 'length_penalty': 1.0, 'no_repeat_ngram_size': 0, 'encoder_no_repeat_ngram_size': 0, 'bad_words_ids': None, 'num_return_sequences': 1, 'chunk_size_feed_forward': 0, 'output_scores': False, 'return_dict_in_generate': False, 'forced_bos_token_id': None, 'forced_eos_token_id': None, 'remove_invalid_values': False, 'exponential_decay_length_penalty': None, 'suppress_tokens': None, 'begin_suppress_tokens': None, 'architectures': ['LlamaForCausalLM'], 'finetuning_task': None, 'id2label': {0: 'LABEL_0', 1: 'LABEL_1'}, 'label2id': {'LABEL_0': 0, 'LABEL_1': 1}, 'tokenizer_class': None, 'prefix': None, 'bos_token_id': 1, 'pad_token_id': None, 'eos_token_id': 2, 'sep_token_id': None, 'decoder_start_token_id': None, 'task_specific_params': None, 'problem_type': None, '_name_or_path': '/cpfs01/user/chenqin.p/model_cached/Llama-2-7b-chat-hf', 'transformers_version': '4.28.1', 'model_type': 'llama', 'output_dir': 'saved/moelora/8experts', 'overwrite_output_dir': True, 'do_train': True, 'do_eval': False, 'do_predict': False, 'evaluation_strategy': 'no', 'prediction_loss_only': False, 'per_device_train_batch_size': 1, 'per_device_eval_batch_size': 1, 'per_gpu_train_batch_size': 'None', 'per_gpu_eval_batch_size': 'None', 'gradient_accumulation_steps': 8, 'eval_accumulation_steps': 'None', 'eval_delay': 0, 'learning_rate': 0.0002, 'weight_decay': 0.0, 'adam_beta1': 0.9, 'adam_beta2': 0.999, 'adam_epsilon': 1e-08, 'max_grad_norm': 1.0, 'num_train_epochs': 1.0, 'max_steps': -1, 'lr_scheduler_type': 'linear', 'warmup_ratio': 0.0, 'warmup_steps': 0, 'log_level': 'passive', 'log_level_replica': 'warning', 'log_on_each_node': True, 'logging_dir': 'saved/moelora/8experts/runs/Mar31_09-41-50_dsw-2874-79656d8585-w7mcn', 'logging_strategy': 'steps', 'logging_first_step': False, 'logging_steps': 100, 'logging_nan_inf_filter': True, 'save_strategy': 'epoch', 'save_steps': 500, 'save_total_limit': 'None', 'save_safetensors': False, 'save_on_each_node': False, 'no_cuda': False, 'use_mps_device': False, 'seed': 42, 'data_seed': 'None', 'jit_mode_eval': False, 'use_ipex': False, 'bf16': False, 'fp16': True, 'fp16_opt_level': 'O1', 'half_precision_backend': 'cuda_amp', 'bf16_full_eval': False, 'fp16_full_eval': False, 'tf32': 'None', 'local_rank': 0, 'xpu_backend': 'None', 'tpu_num_cores': 'None', 'tpu_metrics_debug': False, 'debug': '[]', 'dataloader_drop_last': False, 'eval_steps': 'None', 'dataloader_num_workers': 0, 'past_index': -1, 'run_name': 'saved/moelora/8experts', 'disable_tqdm': False, 'remove_unused_columns': True, 'label_names': 'None', 'load_best_model_at_end': False, 'metric_for_best_model': 'None', 'greater_is_better': 'None', 'ignore_data_skip': False, 'sharded_ddp': '[]', 'fsdp': '[]', 'fsdp_min_num_params': 0, 'fsdp_config': "{'fsdp_min_num_params': 0, 'xla': False, 'xla_fsdp_grad_ckpt': False}", 'fsdp_transformer_layer_cls_to_wrap': 'None', 'deepspeed': 'src/ds.config', 'label_smoothing_factor': 0.0, 'optim': 'adamw_hf', 'optim_args': 'None', 'adafactor': False, 'group_by_length': False, 'length_column_name': 'length', 'report_to': "['wandb']", 'ddp_find_unused_parameters': 'None', 'ddp_bucket_cap_mb': 'None', 'dataloader_pin_memory': True, 'skip_memory_metrics': True, 'use_legacy_prediction_loop': False, 'push_to_hub': False, 'resume_from_checkpoint': 'None', 'hub_model_id': 'None', 'hub_strategy': 'every_save', 'hub_token': '<HUB_TOKEN>', 'hub_private_repo': False, 'gradient_checkpointing': False, 'include_inputs_for_metrics': False, 'fp16_backend': 'auto', 'push_to_hub_model_id': 'None', 'push_to_hub_organization': 'None', 'push_to_hub_token': '<PUSH_TO_HUB_TOKEN>', 'mp_parameters': '', 'auto_find_batch_size': False, 'full_determinism': False, 'torchdynamo': 'None', 'ray_scope': 'last', 'ddp_timeout': 1800, 'torch_compile': False, 'torch_compile_backend': 'None', 'torch_compile_mode': 'None', 'sortish_sampler': False, 'predict_with_generate': False, 'generation_max_length': 196, 'generation_num_beams': 'None', 'generation_config': 'None', 'train_batch_size': 1, 'eval_batch_size': 1}
2024-03-31 09:46:47,917 INFO    Thread-2 (wrapped_target):3306724 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/cpfs01/user/chenqin.p/anaconda3/envs/moe/lib/python3.10/site-packages/urllib3/connectionpool.py", line 712, in urlopen
    self._prepare_proxy(conn)
  File "/cpfs01/user/chenqin.p/anaconda3/envs/moe/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1012, in _prepare_proxy
    conn.connect()
  File "/cpfs01/user/chenqin.p/anaconda3/envs/moe/lib/python3.10/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/cpfs01/user/chenqin.p/anaconda3/envs/moe/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/cpfs01/user/chenqin.p/anaconda3/envs/moe/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/cpfs01/user/chenqin.p/anaconda3/envs/moe/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/cpfs01/user/chenqin.p/anaconda3/envs/moe/lib/python3.10/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/cpfs01/user/chenqin.p/anaconda3/envs/moe/lib/python3.10/ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cpfs01/user/chenqin.p/anaconda3/envs/moe/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/cpfs01/user/chenqin.p/anaconda3/envs/moe/lib/python3.10/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/cpfs01/user/chenqin.p/anaconda3/envs/moe/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cpfs01/user/chenqin.p/anaconda3/envs/moe/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/cpfs01/user/chenqin.p/anaconda3/envs/moe/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/cpfs01/user/chenqin.p/anaconda3/envs/moe/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/cpfs01/user/chenqin.p/anaconda3/envs/moe/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/cpfs01/user/chenqin.p/anaconda3/envs/moe/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 58, in execute
    request = self.session.post(self.url, **post_args)
  File "/cpfs01/user/chenqin.p/anaconda3/envs/moe/lib/python3.10/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/cpfs01/user/chenqin.p/anaconda3/envs/moe/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/cpfs01/user/chenqin.p/anaconda3/envs/moe/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/cpfs01/user/chenqin.p/anaconda3/envs/moe/lib/python3.10/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
